spring:
  profiles:
    active:
    - dev
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  server:
    port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:h2:./hoaxify-prod
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false
hoaxify:
  upload-path: uploads-prod
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:hoaxify-dev
hoaxify:
  upload-path: uploads-dev
---
spring:
  config:
    activate:
      on-profile: test
hoaxify:
  upload-path: uploads-test

  